services:
  js-app:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: js-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "3000:3000"  # Exposed by Dockerfile
    # If your app requires a database or other services, add them below and configure depends_on
    # depends_on:
    #   - db
    # networks:
    #   - appnet

# networks:
#   appnet:
#     driver: bridge
